// Seed Data for Estilo Latino Dance Company

import { DanceStyle, Instructor, ClassScheduleEntry, Package, Service, SiteSettings } from './types';

// ─── DANCE STYLES ───────────────────────────────────────
export const danceStyles: DanceStyle[] = [
  {
    id: '1',
    slug: 'salsa-on1',
    name: 'Salsa On1',
    nameEs: 'Salsa On1',
    tagline: 'ADULTS',
    description: 'Master the classic New York-style Salsa On1 timing. From beginner footwork to advanced shines and partnerwork, build your foundation on one of the most popular Latin dance rhythms.',
    descriptionEs: 'Domina la Salsa estilo Nueva York en tiempo On1. Desde los pasos básicos hasta shines y trabajo en pareja avanzado, construye tu base en uno de los ritmos latinos más populares.',
    heroImage: '/images/salsa-hero.jpg',
    cardImage: '/images/salsa-card.jpg',
    ageGroup: 'adults',
    sortOrder: 1,
    isActive: true,
  },
  {
    id: '2',
    slug: 'salsa-calena',
    name: 'Salsa Caleña',
    nameEs: 'Salsa Caleña',
    tagline: 'ADULTS',
    description: 'Experience the explosive footwork and vibrant energy of Salsa Caleña from Cali, Colombia. Known for its rapid foot patterns and joyful style, it is one of the most exciting Salsa variations.',
    descriptionEs: 'Experimenta el trabajo de pies explosivo y la energía vibrante de la Salsa Caleña de Cali, Colombia. Conocida por sus patrones de pies rápidos y estilo alegre, es una de las variaciones de Salsa más emocionantes.',
    heroImage: '/images/salsa-hero.jpg',
    cardImage: '/images/salsa-card.jpg',
    ageGroup: 'adults',
    sortOrder: 2,
    isActive: true,
  },
  {
    id: '3',
    slug: 'bachata',
    name: 'Bachata',
    nameEs: 'Bachata',
    tagline: 'ADULTS',
    description: 'Experience the sensual and romantic dance of Bachata. Learn traditional and modern styles in our welcoming classes.',
    descriptionEs: 'Experimenta el baile sensual y romántico de la Bachata. Aprende estilos tradicionales y modernos en nuestras clases acogedoras.',
    heroImage: '/images/bachata-hero.jpg',
    cardImage: '/images/bachata-card.jpg',
    ageGroup: 'adults',
    sortOrder: 3,
    isActive: true,
  },
  {
    id: '4',
    slug: 'urban-hiphop',
    name: 'Urban / HipHop',
    nameEs: 'Urbano / HipHop',
    tagline: 'ADULTS',
    description: 'Hip Hop, Reggaeton, and urban styles. Express yourself through high-energy movement with creativity and authentic street-dance technique.',
    descriptionEs: 'Hip Hop, Reggaeton y estilos urbanos. Exprésate a través del movimiento de alta energía con creatividad y técnica auténtica de baile callejero.',
    heroImage: '/images/street-hero.jpg',
    cardImage: '/images/street-card.jpg',
    ageGroup: 'adults',
    sortOrder: 4,
    isActive: true,
  },
  {
    id: '5',
    slug: 'latin-rhythms-kids',
    name: 'Latin Rhythms Kids',
    nameEs: 'Ritmos Latinos para Niños',
    tagline: 'KIDS',
    description: 'Fun and energetic Latin dance classes for children. Learn Salsa, Merengue, and more while building confidence and coordination.',
    descriptionEs: 'Clases de baile latino divertidas y enérgicas para niños. Aprende Salsa, Merengue y más mientras desarrollas confianza y coordinación.',
    heroImage: '/images/kids-latin-hero.jpg',
    cardImage: '/images/kids-latin-card.jpg',
    ageGroup: 'kids',
    sortOrder: 5,
    isActive: true,
  },
  {
    id: '6',
    slug: 'weddings-first-dance',
    name: 'Weddings / First Dance',
    nameEs: 'Bodas / Primer Baile',
    tagline: 'SPECIAL EVENT',
    description: 'Your first dance should be perfect. We create a personalized routine that matches your style, your song, and your skill level. Packages are custom — call us to find out more.',
    descriptionEs: 'Tu primer baile debe ser perfecto. Creamos una rutina personalizada que se adapta a tu estilo, tu canción y tu nivel. Los paquetes son a medida — llámanos para más información.',
    heroImage: '/images/wedding-hero.jpg',
    cardImage: '/images/wedding-hero.jpg',
    ageGroup: 'all',
    sortOrder: 6,
    isActive: true,
    contactOnly: true,
  },
  {
    id: '7',
    slug: 'sweet-16-15',
    name: 'Sweet 16 / 15',
    nameEs: 'Sweet 16 / Quinceañera',
    tagline: 'SPECIAL EVENT',
    description: 'Make your quinceañera or Sweet 16 unforgettable with a custom choreographed dance for you and your court. Packages are custom — call us to find out more.',
    descriptionEs: 'Haz tu quinceañera o Sweet 16 inolvidable con una coreografía personalizada para ti y tu corte. Los paquetes son a medida — llámanos para más información.',
    heroImage: '/images/sweet-sixteen-hero.jpg',
    cardImage: '/images/sweet-sixteen-hero.jpg',
    ageGroup: 'all',
    sortOrder: 7,
    isActive: true,
    contactOnly: true,
  },
  {
    id: '8',
    slug: 'one-on-one-privates',
    name: 'One on One Privates',
    nameEs: 'Clases Privadas',
    tagline: 'ONE-ON-ONE',
    description: 'Personalized private instruction tailored entirely to your goals. Whether you are preparing for an event, mastering technique, or just want focused attention — call us to schedule.',
    descriptionEs: 'Instrucción privada personalizada completamente adaptada a tus objetivos. Ya sea preparándote para un evento, dominando la técnica o simplemente queriendo atención enfocada — llámanos para programar.',
    heroImage: '/images/private-hero.jpg',
    cardImage: '/images/private-card.jpg',
    ageGroup: 'all',
    sortOrder: 8,
    isActive: true,
    contactOnly: true,
  },
  {
    id: '9',
    slug: 'corporate-events',
    name: 'Corporate Events',
    nameEs: 'Eventos Corporativos',
    tagline: 'CORPORATE',
    description: 'Bring the energy of Latin dance to your next corporate event, team-building activity, or company celebration. Packages are custom — call us to find out more.',
    descriptionEs: 'Lleva la energía del baile latino a tu próximo evento corporativo, actividad de equipo o celebración empresarial. Los paquetes son a medida — llámanos para más información.',
    heroImage: '/images/salsa-hero.jpg',
    cardImage: '/images/salsa-card.jpg',
    ageGroup: 'all',
    sortOrder: 9,
    isActive: true,
    contactOnly: true,
  },
];

// ─── INSTRUCTORS ────────────────────────────────────────
export const instructors: Instructor[] = [
  {
    id: '1',
    name: 'Maria Rodriguez',
    specialty: 'Salsa & Bachata',
    bio: 'World Salsa Champion with over 15 years of teaching experience. Maria brings authentic Latin passion to every class.',
    bioEs: 'Campeona Mundial de Salsa con más de 15 años de experiencia enseñando. María trae pasión latina auténtica a cada clase.',
    photo: '/images/instructor-1.jpg',
    socialLinks: [
      { platform: 'instagram', url: 'https://instagram.com/mariasalsa' }
    ],
    sortOrder: 1,
    isActive: true,
  },
  {
    id: '2',
    name: 'Carlos Mendez',
    specialty: 'Street Dance',
    bio: 'Professional choreographer specializing in Hip Hop, Reggaeton, and Afrobeat. Carlos has trained dancers for major productions.',
    bioEs: 'Coreógrafo profesional especializado en Hip Hop, Reggaeton y Afrobeat. Carlos ha entrenado bailarines para grandes producciones.',
    photo: '/images/instructor-2.jpg',
    socialLinks: [
      { platform: 'instagram', url: 'https://instagram.com/carlosdance' }
    ],
    sortOrder: 2,
    isActive: true,
  },
  {
    id: '3',
    name: 'Sofia Garcia',
    specialty: 'Ballet',
    bio: 'Certified ballet instructor with a passion for teaching children. Sofia creates a nurturing environment for young dancers.',
    bioEs: 'Instructora de ballet certificada con pasión por enseñar a niños. Sofía crea un ambiente acogedor para bailarines jóvenes.',
    photo: '/images/instructor-3.jpg',
    socialLinks: [],
    sortOrder: 3,
    isActive: true,
  },
  {
    id: '4',
    name: 'Juan Torres',
    specialty: 'Contemporary',
    bio: 'Contemporary dance artist and choreographer. Juan blends traditional and modern techniques for unique performances.',
    bioEs: 'Artista de danza contemporánea y coreógrafo. Juan mezcla técnicas tradicionales y modernas para actuaciones únicas.',
    photo: '/images/instructor-4.jpg',
    socialLinks: [
      { platform: 'instagram', url: 'https://instagram.com/juantorres' }
    ],
    sortOrder: 4,
    isActive: true,
  },
];

// ─── SCHEDULE ───────────────────────────────────────────
export const schedule: ClassScheduleEntry[] = [
  {
    id: '1',
    styleId: '1',
    dayOfWeek: ['monday', 'wednesday'],
    startTime: '19:00',
    endTime: '20:00',
    level: 'beginner',
    ageGroup: 'adults',
    location: 'Main Studio',
    isActive: true,
    notes: 'Punch card system available',
  },
  {
    id: '2',
    styleId: '1',
    dayOfWeek: ['monday', 'friday'],
    startTime: '20:00',
    endTime: '21:00',
    level: 'intermediate',
    ageGroup: 'adults',
    location: 'Main Studio',
    isActive: true,
  },
  {
    id: '3',
    styleId: '2',
    dayOfWeek: ['wednesday'],
    startTime: '20:00',
    endTime: '21:00',
    level: 'beginner',
    ageGroup: 'adults',
    location: 'Main Studio',
    isActive: true,
  },
  {
    id: '4',
    styleId: '2',
    dayOfWeek: ['wednesday'],
    startTime: '21:00',
    endTime: '22:00',
    level: 'advanced',
    ageGroup: 'adults',
    location: 'Main Studio',
    isActive: true,
  },
  {
    id: '5',
    styleId: '2',
    dayOfWeek: ['tuesday'],
    startTime: '20:00',
    endTime: '21:00',
    level: 'intermediate',
    ageGroup: 'adults',
    location: 'Main Studio',
    isActive: true,
  },
  {
    id: '6',
    styleId: '2',
    dayOfWeek: ['thursday'],
    startTime: '20:00',
    endTime: '21:00',
    level: 'beginner',
    ageGroup: 'adults',
    location: 'Main Studio',
    isActive: true,
  },
  {
    id: '7',
    styleId: '2',
    dayOfWeek: ['thursday'],
    startTime: '19:00',
    endTime: '20:00',
    level: 'advanced',
    ageGroup: 'adults',
    location: 'Main Studio',
    isActive: true,
  },
  {
    id: '8',
    styleId: '4',
    dayOfWeek: ['tuesday', 'friday'],
    startTime: '19:00',
    endTime: '20:00',
    level: 'open',
    ageGroup: 'adults',
    location: 'Main Studio',
    isActive: true,
  },
  {
    id: '9',
    styleId: '4',
    dayOfWeek: ['friday'],
    startTime: '18:00',
    endTime: '19:00',
    level: 'advanced',
    ageGroup: 'adults',
    location: 'Main Studio',
    isActive: true,
  },
  {
    id: '10',
    styleId: '5',
    dayOfWeek: ['tuesday', 'thursday'],
    startTime: '18:00',
    endTime: '19:00',
    level: 'all',
    ageGroup: 'kids',
    location: 'Main Studio',
    isActive: true,
  },
  {
    id: '11',
    styleId: '3',
    dayOfWeek: ['wednesday', 'friday'],
    startTime: '18:00',
    endTime: '19:00',
    level: 'all',
    ageGroup: 'kids',
    location: 'Main Studio',
    isActive: true,
  },
];

// ─── PACKAGES / PRICING ─────────────────────────────────
export const packages: Package[] = [
  {
    id: '1',
    name: 'Single Class',
    nameEs: 'Clase Individual',
    category: 'adults-salsa-bachata',
    price: 2500,
    currency: 'USD',
    classCount: 1,
    expirationMonths: undefined,
    description: 'Try one class. Perfect for first-timers.',
    descriptionEs: 'Prueba una clase. Perfecto para principiantes.',
    paymentLink: 'https://square.link/u/FNs6RSaO?src=sheet',
    sortOrder: 1,
    isActive: true,
  },
  {
    id: '2',
    name: '4 Classes Card',
    nameEs: 'Tarjeta de 4 Clases',
    category: 'adults-salsa-bachata',
    price: 9500,
    currency: 'USD',
    classCount: 4,
    expirationMonths: 1,
    description: 'Best for weekly dancers. Expires in 1 month.',
    descriptionEs: 'Mejor para bailarines semanales. Expira en 1 mes.',
    paymentLink: 'https://square.link/u/zYAZzk20?src=sheet',
    sortOrder: 2,
    isActive: true,
  },
  {
    id: '3',
    name: '8 Classes Card',
    nameEs: 'Tarjeta de 8 Clases',
    category: 'adults-salsa-bachata',
    price: 15000,
    currency: 'USD',
    classCount: 8,
    expirationMonths: 1,
    description: 'Great value. Twice a week for a month.',
    descriptionEs: 'Gran valor. Dos veces por semana durante un mes.',
    paymentLink: 'https://square.link/u/JnmrkHBX?src=sheet',
    sortOrder: 3,
    isActive: true,
  },
  {
    id: '4',
    name: '12 Classes Card',
    nameEs: 'Tarjeta de 12 Clases',
    category: 'adults-salsa-bachata',
    price: 19500,
    currency: 'USD',
    classCount: 12,
    expirationMonths: 2,
    description: 'Most popular. Maximum flexibility over 2 months.',
    descriptionEs: 'Más popular. Máxima flexibilidad durante 2 meses.',
    paymentLink: 'https://square.link/u/qjShNEK8?src=sheet',
    sortOrder: 4,
    isActive: true,
  },
  {
    id: '5',
    name: '15 Classes Card',
    nameEs: 'Tarjeta de 15 Clases',
    category: 'adults-salsa-bachata',
    price: 22500,
    currency: 'USD',
    classCount: 15,
    expirationMonths: 2,
    description: 'Best value. For dedicated dancers.',
    descriptionEs: 'Mejor valor. Para bailarines dedicados.',
    paymentLink: 'https://square.link/u/YzANfSzr?src=sheet',
    sortOrder: 5,
    isActive: true,
  },
  {
    id: '6',
    name: 'Kids Latin Rhythms',
    nameEs: 'Ritmos Latinos para Niños',
    category: 'kids',
    price: null,
    currency: 'USD',
    description: 'Monthly enrollment for kids ages 5-12.',
    descriptionEs: 'Inscripción mensual para niños de 5 a 12 años.',
    paymentLink: 'https://square.link/u/9GoE8ILA?src=sheet',
    sortOrder: 6,
    isActive: true,
  },
  {
    id: '7',
    name: 'Urban / HipHop',
    nameEs: 'Urbano / HipHop',
    category: 'adults-street',
    price: null,
    currency: 'USD',
    description: 'Monthly or drop-in rates available.',
    descriptionEs: 'Tarifas mensuales o por clase disponibles.',
    paymentLink: 'https://square.link/u/eJjcA1AE?src=sheet',
    sortOrder: 7,
    isActive: true,
  },
  {
    id: '8',
    name: 'Weddings / First Dance',
    nameEs: 'Bodas / Primer Baile',
    category: 'event',
    price: null,
    currency: 'USD',
    description: 'Custom choreography for your special day. Pricing depends on the number of sessions and routine complexity. Call us to get started.',
    descriptionEs: 'Coreografía personalizada para tu día especial. El precio depende del número de sesiones y la complejidad de la rutina. Llámanos para comenzar.',
    sortOrder: 8,
    isActive: true,
  },
  {
    id: '9',
    name: 'Sweet 16 / 15',
    nameEs: 'Sweet 16 / Quinceañera',
    category: 'event',
    price: null,
    currency: 'USD',
    description: 'A fully custom choreography package for you and your court. Call us to find out what is included and get a quote.',
    descriptionEs: 'Un paquete de coreografía completamente personalizado para ti y tu corte. Llámanos para saber qué está incluido y obtener un presupuesto.',
    sortOrder: 9,
    isActive: true,
  },
  {
    id: '10',
    name: 'One on One Privates',
    nameEs: 'Clases Privadas',
    category: 'private',
    price: null,
    currency: 'USD',
    description: 'Personalized private lessons tailored to your goals and schedule. Rates vary — call us to discuss options.',
    descriptionEs: 'Clases privadas personalizadas adaptadas a tus objetivos y horario. Las tarifas varían — llámanos para hablar sobre las opciones.',
    sortOrder: 10,
    isActive: true,
  },
  {
    id: '11',
    name: 'Corporate Events',
    nameEs: 'Eventos Corporativos',
    category: 'event',
    price: null,
    currency: 'USD',
    description: 'Custom dance experiences for team-building, company parties, and corporate celebrations. Call us for a custom quote.',
    descriptionEs: 'Experiencias de baile personalizadas para team-building, fiestas de empresa y celebraciones corporativas. Llámanos para un presupuesto personalizado.',
    sortOrder: 11,
    isActive: true,
  },
];

// ─── SERVICES ───────────────────────────────────────────
export const services: Service[] = [
  {
    id: '1',
    slug: 'sweet-sixteen',
    name: 'Sweet Sixteen',
    nameEs: 'Quinceañera',
    description: 'Make your celebration unforgettable with a custom choreographed dance. We specialize in Salsa, Bachata, and contemporary routines for you and your court.',
    descriptionEs: 'Haz tu celebración inolvidable con una coreografía personalizada. Nos especializamos en rutinas de Salsa, Bachata y contemporáneo para ti y tu corte.',
    heroImage: '/images/sweet-sixteen-hero.jpg',
    gallery: ['/images/sweet-16-1.jpg', '/images/sweet-16-2.jpg'],
    ctaType: 'contact',
    ctaLabel: 'Book Your Choreography',
    ctaLabelEs: 'Reserva Tu Coreografía',
    sortOrder: 1,
  },
  {
    id: '2',
    slug: 'wedding-dance',
    name: 'Wedding Dance',
    nameEs: 'Baile de Boda',
    description: 'Your first dance should be perfect. We create personalized routines that match your style and skill level. Impress your guests!',
    descriptionEs: 'Tu primer baile debe ser perfecto. Creamos rutinas personalizadas que coinciden con tu estilo y nivel de habilidad. ¡Impresiona a tus invitados!',
    heroImage: '/images/wedding-hero.jpg',
    gallery: ['/images/wedding-1.jpg', '/images/wedding-2.jpg'],
    ctaType: 'contact',
    ctaLabel: 'Start Planning',
    ctaLabelEs: 'Comenzar a Planificar',
    sortOrder: 2,
  },
  {
    id: '3',
    slug: 'school-choreography',
    name: 'School Choreography',
    nameEs: 'Coreografía Escolar',
    description: 'Professional choreography for school performances, talent shows, and competitions. We work with groups of all ages and skill levels.',
    descriptionEs: 'Coreografía profesional para presentaciones escolares, shows de talento y competencias. Trabajamos con grupos de todas las edades y niveles.',
    heroImage: '/images/school-hero.jpg',
    gallery: ['/images/school-1.jpg'],
    ctaType: 'contact',
    ctaLabel: 'Get a Quote',
    ctaLabelEs: 'Obtener Cotización',
    sortOrder: 3,
  },
  {
    id: '4',
    slug: 'private-lessons',
    name: 'Private Lessons',
    nameEs: 'Clases Privadas',
    description: 'One-on-one instruction tailored to your goals. Whether preparing for an event or mastering technique, our instructors provide focused attention.',
    descriptionEs: 'Instrucción individual adaptada a tus objetivos. Ya sea preparándote para un evento o dominando la técnica, nuestros instructores brindan atención enfocada.',
    heroImage: '/images/private-lessons-hero.jpg',
    gallery: [],
    ctaType: 'contact',
    ctaLabel: 'Schedule Lesson',
    ctaLabelEs: 'Programar Clase',
    sortOrder: 4,
  },
];

// ─── SITE SETTINGS ──────────────────────────────────────
export const siteSettings: SiteSettings = {
  studioName: 'Estilo Latino Dance Company',
  studioNameShort: 'Estilo Latino',
  tagline: 'Dance Academy',
  address: '345 Morris Ave Ste 1B',
  addressLine2: '',
  city: 'Elizabeth',
  state: 'NJ',
  zip: '07208',
  phone: '+1 (201) 878-8977',
  whatsapp: '+12018788977',
  email: 'info@EstiloLatinoDance.com',
  googleMapsEmbed: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3026.8!2d-74.2107!3d40.6644!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zNDDCsDM5JzUxLjgiTiA3NMKwMTInMzguNSJX!5e0!3m2!1sen!2sus!4v1234567890123!5m2!1sen!2sus',
  socialLinks: [
    { platform: 'Facebook', url: 'https://facebook.com/EstiloLatinoDC', label: 'EstiloLatinoDC' },
    { platform: 'Instagram', url: 'https://instagram.com/estilo.latino', label: '@estilo.latino' },
    { platform: 'TikTok', url: 'https://tiktok.com/@estilolatino', label: '@estilolatino' },
    { platform: 'YouTube', url: 'https://youtube.com/@estilolatino', label: 'Estilo Latino' },
  ],
  businessHours: [
    { day: 'Monday', open: '18:00', close: '22:00', isClosed: false },
    { day: 'Tuesday', open: '18:00', close: '22:00', isClosed: false },
    { day: 'Wednesday', open: '18:00', close: '22:00', isClosed: false },
    { day: 'Thursday', open: '18:00', close: '22:00', isClosed: false },
    { day: 'Friday', open: '18:00', close: '22:00', isClosed: false },
    { day: 'Saturday', open: '10:00', close: '14:00', isClosed: false },
    { day: 'Sunday', open: '', close: '', isClosed: true },
  ],
  partnerLogos: [],
  logo: '/images/logo.png',
  announcementBar: {
    text: 'New classes starting soon! First class FREE for new students.',
    textEs: '¡Nuevas clases comenzando pronto! Primera clase GRATIS para nuevos estudiantes.',
    isActive: true,
    link: '/packages',
  },
};
